// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGMkgJ_TZJBQGCyucr1ketAcp-_0QLCDc',
    appId: '1:631914466411:web:9b826baa06737f9bb2f52e',
    messagingSenderId: '631914466411',
    projectId: 'drassistant-d7b5f',
    authDomain: 'drassistant-d7b5f.firebaseapp.com',
    storageBucket: 'drassistant-d7b5f.firebasestorage.app',
    measurementId: 'G-RGW9M564ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHEqb6yfm_Qv5OUpU8HCIvvYyKCrtfvE4',
    appId: '1:631914466411:android:c57320426a5779fdb2f52e',
    messagingSenderId: '631914466411',
    projectId: 'drassistant-d7b5f',
    storageBucket: 'drassistant-d7b5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkv7nl4q65ngjKnIqItU0bnUeg9NwzeQE',
    appId: '1:631914466411:ios:aa284a7daecf138eb2f52e',
    messagingSenderId: '631914466411',
    projectId: 'drassistant-d7b5f',
    storageBucket: 'drassistant-d7b5f.firebasestorage.app',
    iosBundleId: 'com.example.drassistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkv7nl4q65ngjKnIqItU0bnUeg9NwzeQE',
    appId: '1:631914466411:ios:aa284a7daecf138eb2f52e',
    messagingSenderId: '631914466411',
    projectId: 'drassistant-d7b5f',
    storageBucket: 'drassistant-d7b5f.firebasestorage.app',
    iosBundleId: 'com.example.drassistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGMkgJ_TZJBQGCyucr1ketAcp-_0QLCDc',
    appId: '1:631914466411:web:aac865a67ed46550b2f52e',
    messagingSenderId: '631914466411',
    projectId: 'drassistant-d7b5f',
    authDomain: 'drassistant-d7b5f.firebaseapp.com',
    storageBucket: 'drassistant-d7b5f.firebasestorage.app',
    measurementId: 'G-9TMH6D2V64',
  );
}
